package Cisco::ACI::Stats::Curr::L2IngrBytes;

use Moose;

extends 'Cisco::ACI::Stats::Curr';

has 'dropAvg'		=> (is => 'rw', isa => 'Str');
has 'dropBase'		=> (is => 'rw', isa => 'Str');
has 'dropCum'		=> (is => 'rw', isa => 'Int');
has 'dropLast'		=> (is => 'rw', isa => 'Str');
has 'dropMax'		=> (is => 'rw', isa => 'Str');
has 'dropMin'		=> (is => 'rw', isa => 'Str');
has 'dropPer'		=> (is => 'rw', isa => 'Int');
has 'dropRate'		=> (is => 'rw', isa => 'Int');
has 'dropSpct'		=> (is => 'rw', isa => 'Int');
has 'dropThr'		=> (is => 'rw', isa => 'Str');
has 'dropTr'		=> (is => 'rw', isa => 'Int');
has 'dropTrBase'	=> (is => 'rw', isa => 'Int');
has 'floodAvg'		=> (is => 'rw', isa => 'Str');
has 'floodBase'		=> (is => 'rw', isa => 'Str');
has 'floodCum'		=> (is => 'rw', isa => 'Int');
has 'floodLast'		=> (is => 'rw', isa => 'Str');
has 'floodMax'		=> (is => 'rw', isa => 'Str');
has 'floodMin'		=> (is => 'rw', isa => 'Str');
has 'floodPer'		=> (is => 'rw', isa => 'Int');
has 'floodRate'		=> (is => 'rw', isa => 'Int');
has 'floodSpct'		=> (is => 'rw', isa => 'Int');
has 'floodThr'		=> (is => 'rw', isa => 'Str');
has 'floodTr'		=> (is => 'rw', isa => 'Int');
has 'floodTrBase'	=> (is => 'rw', isa => 'Int');
has 'index'		=> (is => 'rw', isa => 'Int');
has 'multicastAvg'	=> (is => 'rw', isa => 'Int');
has 'multicastBase'	=> (is => 'rw', isa => 'Int');
has 'multicastCum'	=> (is => 'rw', isa => 'Int');
has 'multicastLast'	=> (is => 'rw', isa => 'Int');
has 'multicastMax'	=> (is => 'rw', isa => 'Int');
has 'multicastMin'	=> (is => 'rw', isa => 'Int');
has 'multicastPer'	=> (is => 'rw', isa => 'Int');
has 'multicastRate'	=> (is => 'rw', isa => 'Int');
has 'multicastSpct'	=> (is => 'rw', isa => 'Int');
has 'multicastThr'	=> (is => 'rw', isa => 'Int');
has 'multicastTr'	=> (is => 'rw', isa => 'Int');
has 'multicastTrBase'	=> (is => 'rw', isa => 'Int');
has 'unicastAvg'	=> (is => 'rw', isa => 'Int');
has 'unicastBase'	=> (is => 'rw', isa => 'Int');
has 'unicastCum'	=> (is => 'rw', isa => 'Int');
has 'unicastLast'	=> (is => 'rw', isa => 'Int');
has 'unicastMax'	=> (is => 'rw', isa => 'Int');
has 'unicastMin'	=> (is => 'rw', isa => 'Int');
has 'unicastPer'	=> (is => 'rw', isa => 'Int');
has 'unicastRate'	=> (is => 'rw', isa => 'Int');
has 'unicastSpct'	=> (is => 'rw', isa => 'Int');
has 'unicastThr'	=> (is => 'rw', isa => 'Int');
has 'unicastTr'		=> (is => 'rw', isa => 'Int');
has 'unicastTrBase'	=> (is => 'rw', isa => 'Int');

1;
